### ISSUE TITLE
An error occurs when running the make.sh file using A800

### ISSUE THREAD

**Issue by shulil1** [KuanchihHuang/MonoDTR#17]
The error message is as follows：ValueError: Unknown CUDA arch (8.0) or GPU not supported

**Comment by Akos0628** [comment]
I ran into something similar when running on an RTX 30 series gpu with Cuda 10. I think I was able to resolve this issue by finding the file in the cuda lib that threw this error, and just added the 8.0 arch to the list of supported architectures. But along the way I ran into more problems and just went with a newer Cuda version.
this did the trick:
`conda create -n mono python=3.7 pytorch==1.8.0 torchvision==0.9.0 torchaudio==0.8.0 cudatoolkit=11.1 numba tqdm -c pytorch -c conda-forge`

**Comment by shulil1** [comment]
> I ran into something similar when running on an RTX 30 series gpu with Cuda 10. I think I was able to resolve this issue by finding the file in the cuda lib that threw this error, and just added the 8.0 arch to the list of supported architectures. But along the way I ran into more problems and just went with a newer Cuda version. this did the trick: `conda create -n mono python=3.7 pytorch==1.8.0 torchvision==0.9.0 torchaudio==0.8.0 cudatoolkit=11.1 numba tqdm -c pytorch -c conda-forge`

So kind of you! Thx a lot! :D
