### ISSUE TITLE
How can i get the 'depth_gt'? 

### ISSUE THREAD

**Issue by Da1symeeting1** [KuanchihHuang/MonoDTR#21]
![image](https://github.com/user-attachments/assets/0fe37cab-9a63-480b-b9d4-c16e3568fe4a)
I can't find the code where the 'depth_gt' comes from, could you please point out the code? please.
Thank you all.

**Comment by KuanchihHuang** [comment]
Hi, depth_gt is the ground truth of depth for training. You can check here: https://github.com/KuanchihHuang/MonoDTR/blob/8a40c4807b9d354d1cd12838ec094d9d70d40f72/visualDet3D/networks/pipelines/trainers.py#L37
