### ISSUE TITLE
No such file or directory: './workdirs/MonoDTR/output/training/imdb.pkl'

### ISSUE THREAD

**Issue by shijinghuihub** [KuanchihHuang/MonoDTR#3]

**Comment by shijinghuihub** [comment]
I found in scripts/imdb_precompute_3d.py and scripts/imdb_precompute_test.py

**Comment by KuanchihHuang** [comment]
Hi, you can follow the instruction in [Data.md](https://github.com/KuanchihHuang/MonoDTR/blob/main/DATA.md) to generate imdb file.
