### ISSUE TITLE
I don't know why I could not reproduce the validation results.

### ISSUE THREAD

**Issue by jichaofeng** [KuanchihHuang/MonoDTR#5]
Thank you for releasing the code. For the Car class, Our validation results are:
bev  AP:27.31, 21.58, 18.66
3d   AP:19.78, 15.99, 13.62

**Comment by KuanchihHuang** [comment]
Hi, I have no idea why the lower performance. Can you provide more information? 
Have you followed the instructions to generate data and depth ground truth. 
And also, this repo only supports single-GPU training.

**Comment by jichaofeng** [comment]
we have followed the instructions to generate data and depth ground truth, and used single GPU training. the version of pytorch is 1.1.

**Comment by KuanchihHuang** [comment]
The torch version lower than 1.3 maybe can not successfully compile the deform Conv layer.
Can you get reasonable performance from the [pretrained weight](https://drive.google.com/file/d/1mQzqjnosra5JE1sJKzSRzdn3R010G0Gh/view)?

**Comment by KuanchihHuang** [comment]
Close due to inactivity.

**Comment by jichaofeng** [comment]
Sorry for my late reply. We try to load the pretrained model. There is some error:
RuntimeError: Error(s) in loading state_dict for MonoDTR:
	size mismatch for bbox_head.reg_feature_extraction.3.weight: copying a param with shape torch.Size([256, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([576, 256, 3, 3]).
