### ISSUE TITLE
Visualization the results

### ISSUE THREAD

**Issue by idjoopal** [KuanchihHuang/MonoDTR#7]
Hello, I was impressed by your code, so I proceeded with the learning myself.
By the way, what code should I use to visualize the validation results?
Is there a document or github repo that I can refer to?

**Comment by KuanchihHuang** [comment]
Hi, visualDet3D provides a good [notebook](https://github.com/Owen-Liuyuxuan/visualDet3D/blob/master/demos/visualize_test_center.ipynb) for better visualization.

**Comment by idjoopal** [comment]
Okay, thank you. Then where can I get a reference for visualizing Bird's Eye View?
There was a visualization in the paper, but it's hard to find.
I'm a stranger in this field, so I apologize if it's too much of a rudimentary question. Have a nice day!

**Comment by idjoopal** [comment]
@KuanchihHuang 
Okay, thank you. Then where can I get a reference for visualizing Bird's Eye View?
There was a visualization in the paper, but it's hard to find.
I'm a stranger in this field, so I apologize if it's too much of a rudimentary question. Have a nice day!

**Comment by KuanchihHuang** [comment]
Hi, the author of [SMOKE](https://github.com/lzccccc/SMOKE) provides a good [script](https://github.com/lzccccc/3d-bounding-box-estimation-for-autonomous-driving/blob/master/utils/visualization3Dbox.py) for visualization. BTW you need to change the output filename to match the format.

**Comment by idjoopal** [comment]
So kind of you! Thx a lot! :D
