### ISSUE TITLE
How to get the anchor clusters?

### ISSUE THREAD

**Issue by liuxubit** [KuanchihHuang/MonoDTR#8]
Hello:
How to get the anchor clusters?
Do you have a code for reference?

**Comment by KuanchihHuang** [comment]
Hi, anchor statistics can be obtained through [imdb_precompute_3d.py](https://github.com/KuanchihHuang/MonoDTR/blob/main/scripts/imdb_precompute_3d.py). You can follow the instructions in [Data.md](https://github.com/KuanchihHuang/MonoDTR/blob/main/DATA.md) to generate them.

**Comment by KuanchihHuang** [comment]
Close due to inactivity.
